# Generated by Django 5.2.3 on 2025-06-10 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('precio_dia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carritos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_noche', models.IntegerField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hoteles', to='api.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_factura', models.DateTimeField(auto_now_add=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('cuil', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=255)),
                ('numero_calle', models.CharField(max_length=20)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=10, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='facturas', to='api.pagos')),
            ],
        ),
        migrations.AddField(
            model_name='ciudades',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.paises'),
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('personas', models.IntegerField()),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_regreso', models.DateTimeField()),
                ('hora_salida', models.TimeField()),
                ('pagado', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.autos')),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paquetes_destino', to='api.ciudades')),
                ('ciudad_salida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paquetes_salida', to='api.ciudades')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.hoteles')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paquetes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pagos',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagos', to='api.paquetes'),
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas_usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carrito', to='api.carritos')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paquete', to='api.paquetes')),
            ],
        ),
    ]
