# Generated by Django 5.2.3 on 2025-06-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='codigo_activacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
