# Generated by Django 5.2.3 on 2025-06-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_reservas_usuario_carrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='dueno',
            field=models.BooleanField(default=False),
        ),
    ]
