# Generated by Django 5.2.3 on 2025-06-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ciudades_latitud_alter_ciudades_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudades',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ciudades',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
