# Generated by Django 5.2.3 on 2025-06-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ciudades_latitud_alter_ciudades_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
