# Generated by Django 5.2.3 on 2025-06-12 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_paquetes_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritos',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='carritos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carritos',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
