# Generated by Django 5.2.3 on 2025-06-12 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_carritos_id_usuario_alter_carritos_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='historica', to='api.facturas')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='historica', to='api.pagos')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='historica', to='api.paquetes')),
            ],
        ),
    ]
