# Generated by Django 5.2.3 on 2025-06-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_historica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritos',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
