# Generated by Django 5.2.3 on 2025-06-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_carritos_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteles',
            name='personas',
            field=models.IntegerField(default=1),
        ),
    ]
