# Generated by Django 5.2.3 on 2025-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_aviones_remove_paquetes_ciudad_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviones',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
