# Generated by Django 5.2.3 on 2025-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_aviones_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
