# Generated by Django 5.2.3 on 2025-06-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_vuelos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientos',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
