# Generated by Django 5.2.3 on 2025-06-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_asientos_reservado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientos',
            name='estado',
        ),
        migrations.AddField(
            model_name='asientos',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
    ]
