# Generated by Django 5.2.3 on 2025-06-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_paquetes_asiento_ida_paquetes_asiento_vuelta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquetes',
            name='asiento_ida',
        ),
        migrations.RemoveField(
            model_name='paquetes',
            name='asiento_vuelta',
        ),
        migrations.AddField(
            model_name='paquetes',
            name='asiento_ida',
            field=models.ManyToManyField(blank=True, null=True, related_name='paquetes_asiento_ida', to='api.asientos'),
        ),
        migrations.AddField(
            model_name='paquetes',
            name='asiento_vuelta',
            field=models.ManyToManyField(blank=True, null=True, related_name='paquetes_asiento_vuelta', to='api.asientos'),
        ),
    ]
