# Generated by Django 5.2.3 on 2025-06-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_paquetes_asiento_ida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50),
        ),
    ]
