# Generated by Django 5.2.3 on 2025-06-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_paquetes_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historica',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historica', to='api.paquetes'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.paquetes'),
        ),
        migrations.AlterField(
            model_name='reservas_usuario',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquete', to='api.paquetes'),
        ),
    ]
