# Generated by Django 5.2.3 on 2025-06-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_historica_paquete_alter_pagos_paquete_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personas',
        ),
    ]
