# Generated by Django 5.2.3 on 2025-06-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_personas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='total',
            field=models.FloatField(blank=True),
        ),
    ]
